add rollback step

diff --git a/.github/workflows/regtech-app.yml b/.github/workflows/regtech-app.yml
--- a/.github/workflows/regtech-app.yml
+++ b/.github/workflows/regtech-app.yml
@@ -243,3 +243,14 @@ jobs:
       run: |
         sed -i "s|image: REPOSITORY_TAG|image: 611512058022.dkr.ecr.us-east-1.amazonaws.com/regtech-app:${GITHUB_RUN_NUMBER}|g" ./deploy.yml
         kubectl apply -f ./deploy.yml
+
+    - name: Check Deployment Status 
+      id: check-status 
+      run: |
+        kubectl rollot status deployment.apps/regtech-app-deployment || exit 
+
+    - name: Rollback Deployment 
+      if: failure()
+      run: | 
+        echo "Deployment failed. Rolling back..."
+        kubectl rollout undo deployment.apps/regtech-app-deployment
